### ISSUE TITLE
utilite de ft_strdup_free ??

### ISSUE THREAD

**Issue by StephaneVogrig** [StephaneVogrig/08_minishell#16]
Quelle est l'utilite de mallloc une nouvelle str, de copier l,ancienne et de free l'ancienne ?
Pourquoi ne pas directement utiliser l'ancienne ?

**Comment by Stephmo1984** [comment]
Utiilise dans fonction->	node_HOME_cpy(t_env *env)

Cree un node type INTERNAL qui contient une copie de HOME
fait pour gerer  " cd ~ "

ici ----> node->value = ft_strdup_free(create_HOME_path(env));

mais on pourra supprimer car la gestion du ~ n'est pas demande dans le sujet (?)
