### ISSUE TITLE
NORM : to do

### ISSUE THREAD

**Issue by Stephmo1984** [StephaneVogrig/08_minishell#56]
**TO_DO :**
./src/execution/exec_builtin.c: Error!
Error: MISSING_IDENTIFIER   (line:  15, col:  44):	missing type qualifier or identifier in function arguments
Error: MISSING_IDENTIFIER   (line:  15, col:  53):	missing type qualifier or identifier in function arguments

./src/data/pipeline.c: Error!
Error: TOO_MANY_FUNCS       (line:  73, col:   1):	Too many functions in file

**DONE :** 
./src/execution/exec_builtin.c: Error!
Error: TOO_MANY_LINES       (line:  65, col:   1):	Function has more than 25 lines

./include/buff/buff.h: Error!
Error: HEADER_PROT_NAME     (line:  13, col:   9):	Wrong header protection name
Error: HEADER_PROT_NODEF    (line:  35, col:   1):	Header protection not containing #42 

./src/environment/env_pwd.c: Error!
Error: TOO_MANY_LINES       (line:  43, col:   1):	Function has more than 25 lines

**Comment by StephaneVogrig** [comment]
DONE

./src/data/pipeline.c: Error!
Error: TOO_MANY_FUNCS (line: 73, col: 1): Too many functions in file
